service: ${env:STACK_NAME}-${env:SUBDOMAIN}-p1-dependency

frameworkVersion: ^2.17.0

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 300
  memorySize: 128
  region: ${env:REGION}
  stage: ${env:ENV}

resources:
  myDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId : ${env:P1PUBLICZONEID}
      Name: ${env:PUBLICZONENAME}
      ResourceRecords: ${env:PUBLICZONENSRECORD}
      TTL: '300'
      Type: A
