service: ${env:STACK_NAME}-${env:SUBDOMAIN}-p1-dependency

frameworkVersion: ^2.17.0

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 300
  memorySize: 128
  region: ${env:REGION}
  stage: ${env:ENV}


custom:

resources:
  NSRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: This is test record from automation
      HostedZoneId : ${env:P1PUBLICZONEID}
      Name: ${env:PUBLICZONENAME}
      ResourceRecords: ${env:PUBLICZONENSRECORD}
      TTL: '60'
      Type: NS
