service: ${env:STACK_NAME}-${env:SUBDOMAIN}-secret-arn-export

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 300
  memorySize: 128
  region: ${env:REGION}
  stage: ${env:ENV}


resources:
  Resources:
    S3Bucket:
      Type: 'AWS::S3::Bucket'
      Properties: []

  Outputs:
    AUTOMATED:
      Description: Automated exporting secret name
      Value: Automated
      Export:
        Name: Automated

