AWSTemplateFormatVersion: '2010-09-09'
Description: This is Route53 Public Hosted Zone cloudformation template for core Practera infrastructure
  design.
Metadata:
  Authors:
    Description: Sunil and Mihai (sunil@practera.com/mihai@practera.com) based on
      AWS quickstart/widdix and best practise.
  License:
    Description: Copyright 2020 Intersective PTY LTD and its affiliates. All Rights
      Reserved.

Parameters:
  StackName:
    ConstraintDescription: This will be unique string to represent our stack.
    Default: beta
    Description: A client/project/product unique name for the stack to idnetify later.
      This string can include numbers, lowercase letters, uppercase letters, and hyphens
      (-). It cannot start or end with a hyphen (-).
    Type: String
    AllowedValues: [au,us,uk,p2,lf,nu,alpha,beta]
  Env:
    Description: Environment type.
    Default: stage
    Type: String
    AllowedValues:
      - sandbox
      - stage
      - live
  PublicHostedZoneName:
    Description: 'The name of the existing hosted zone.'
    Type: String

Resources:
  HostedZone:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      HostedZoneConfig:
        Comment: !Sub "${PublicHostedZoneName} public DNS zone"
      Name: !Ref PublicHostedZoneName
      HostedZoneTags: 
      - 
        Key: 'Name'
        Value: !Sub '${StackName}-${PublicHostedZoneName}-${Env}'
Outputs:
  StackName:
    Description: 'Stack name.'
    Value: !Sub '${AWS::StackName}'
  PublicHostedZoneName:
    Description: 'The name of the hosted zone.'
    Value: !Ref PublicHostedZoneName
    Export:
      Name: !Sub '${StackName}-PublicHostedZoneName-${Env}'
  PublicHostedZoneId:
    Description: 'The ID of the hosted zone.'
    Value: !Ref HostedZone
    Export:
      Name: !Sub '${StackName}-PublicHostedZoneId-${Env}'
  PublicHostedZoneNSRecord:
    Description: 'The Name Server record for Hosted Zone.'
    Value:  !Join [',', !GetAtt HostedZone.NameServers]
    Export:
      Name: !Sub '${StackName}-PublicHostedZoneNSRecord-${Env}'