AWSTemplateFormatVersion: '2010-09-09'
Description: This is Route53 Public Hosted Zone cloudformation template for core Practera infrastructure
  design.
Metadata:
  Authors:
    Description: Sunil and Mihai (sunil@practera.com/mihai@practera.com) based on
      AWS quickstart/widdix and best practise.
  License:
    Description: Copyright 2020 Intersective PTY LTD and its affiliates. All Rights
      Reserved.

Parameters:
  StackName:
    ConstraintDescription: This will be unique string to represent our stack.
    Default: beta
    Description: A client/project/product unique name for the stack to idnetify later.
      This string can include numbers, lowercase letters, uppercase letters, and hyphens
      (-). It cannot start or end with a hyphen (-).
    Type: String
    AllowedValues: [au,us,uk,p2,lf,nu,alpha,beta,shared]
  Env:
    Description: Environment type.
    Default: stage
    Type: String
    AllowedValues:
      - sandbox
      - stage
      - live
  PrivateHostedZoneName:
    Description: 'The name of the existing hosted zone.'
    Type: String

Resources:
  PrivateHostedZone:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      HostedZoneConfig:
        Comment: !Sub "${PrivateHostedZoneName} private DNS zone"
      Name: !Ref PrivateHostedZoneName
      VPCs:
      - VPCId: {'Fn::ImportValue': !Sub '${StackName}-VPC-${Env}'}
        VPCRegion: !Ref 'AWS::Region'
      HostedZoneTags: 
      - 
        Key: 'Name'
        Value: !Sub '${StackName}-${PrivateHostedZoneName}-${Env}'
Outputs:
  StackName:
    Description: 'Stack name.'
    Value: !Sub '${AWS::StackName}'
  PrivateHostedZoneName:
    Description: 'The name of the hosted zone.'
    Value: !Ref PrivateHostedZoneName
    Export:
      Name: !Sub '${StackName}-PrivateHostedZoneName-${Env}'
  PrivateHostedZoneID:
    Description: 'The ID of the hosted zone.'
    Value: !Ref PrivateHostedZone
    Export:
      Name: !Sub '${StackName}-PrivateHostedZoneID-${Env}'



